repos:
  - repo: local
    hooks:
      - id: database-schema-validation
        name: Database Schema Validation
        entry: python scripts/validate_database_schema.py --fail-on-errors
        language: system
        files: ^(alembic/versions/.*\.py|app/database/models\.py|app/models/.*)$
        require_serial: true
        description: 'Validate database schema consistency between models and migrations'

      - id: migration-integration-tests
        name: Migration Integration Tests
        entry: python -m pytest tests/integration/test_database_schema_validation.py -v --tb=short
        language: system
        files: ^(alembic/versions/.*\.py|app/database/models\.py)$
        require_serial: true
        description: 'Run integration tests for database schema changes'

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=88, --extend-ignore=E203]